steps:
- name: bash
  script: |
    #!/usr/bin/env bash
    ls; ls *
- name: node:16
  entrypoint: npm
  args: ['install']
- name: node:16
  entrypoint: npm
  args: ['run','build']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'function-001', '--trigger-topic=data_sync_topic', '--runtime', 'nodejs16', '--entry-point', 'handler']
  dir: 'build'


