steps:
- name: 'npm'
  args: ['install']
  dir: '/'
- name: 'npm'
  args: ['build']
  dir: '/'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'function-001', '--trigger-topic=data_sync_topic', '--trigger-event=google.pubsub.topic.publish','--runtime', 'nodejs16', '--entry-point', 'handler']
  dir: '/build/'